version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: healx_db
      POSTGRES_USER: healx_admin
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "5672:5672"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"